---
# ansible/inventory/hosts.yml

all:
  children:

    ec2_ubuntu:
      hosts:

        zt-target:
          ansible_connection:                  aws_ssm
          ansible_aws_ssm_region:              us-east-2
          ansible_aws_ssm_instance_id:         REPLACE_WITH_YOUR_INSTANCE_ID
          ansible_aws_ssm_bucket_name:         REPLACE_WITH_SSM_BUCKET_ID
          ansible_aws_ssm_bucket_endpoint_url: REPLACE_WITH_SSM_ENDPOINT
          ansible_python_interpreter:          /usr/bin/python3
          instance_role:                       app
          instance_environment:                test
          instance_owner:                      yourself